 image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server
---
kind: pipeline
type: kubernetes
name: cypress-test

platform:
  os: linux
  arch: amd64

steps:
- name: dev_cypress_test
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-cypress:10.3.0-node16
  commands:
  - ./cypress-extract-env.sh ./helm/dev.yaml
  - cat ./cypress-env.sh
  - export $(cat ./cypress-env.sh | xargs)
  - apt-get update && apt-get upgrade -y
  - ./drone-cypress-test-script.sh dev
  when:
    branch:
    - version-*
    - cypress-drone
    event:
    - push
  failure: ignore
